### ISSUE TITLE
Animation Issue: Animaton New sometimes won't delay 

### ISSUE THREAD

**Issue by kailinc** [kailinc/react-2048#11]
This is very annoying in the standpoint of UI. Sometimes the animation new would not delay or happen instantly. It is as if it ignored the animation duration and animation delay I set up. This usually happens when there is a big shift for the board. 

```css
.new {
  transform: scale(0);
  animation: new 0.25s linear forwards;
  animation-delay: 0.2s;
}

.hor-1 {
  animation: slideRight1 0.1s linear forwards;
}
```
